### ISSUE TITLE
Add Changelog

### ISSUE THREAD

**Issue by JMuff22** [AqueductHub/aqueductcore#31]
Hi, would you be willing to add a changelog file describing changes between releases? I noticed that new features have been added to the development version, however to find what features have been added I need to look through the PR/commit history. Would you consider adding a changelog?

Regards,
Jake

**Comment by safeamiiir** [comment]
Hey Jake,
A changelog and release note will be in place quite soon, but till then we'll keep this issue as a place for further potential conversation and discussions on it.

Thanks for bringing it up!

**Comment by JMuff22** [comment]
I would actually like to keep this open. It seems in https://github.com/AqueductHub/aqueductcore/commit/5dbc428822a5e7c5fd2bf46d4b914f366e6dc201 a flag was added to the CI to auto generate release notes. However, as a user, it would be good to see what in particular changed between versions in a `CHANGELOG.md` or similar rather than rely on Github automatically generated release notes.

**Comment by safeamiiir** [comment]
Sure things @JMuff22.
Although we include changes in the release note per release, but it's making it more visible to have `CHANGELOG.md` as well. It was not the case before, but now, with more releases, it's a very good to have.

I'll make a new ticket in the project board and will be picked up.

And thanks for your contribution.

**Comment by safeamiiir** [comment]
Related ticket #118

**Comment by samiralavi** [comment]
I have started working on this, to implement the following changes:
1- There will be a new file `CHANGELOG.md` in the repo.
2- There will be a new CI workflow to update the changelog on every PR merge into main (we have already established we continue using Gitflow branching strategy)
3- This `CHANGELOG.md` file will be used in the release notes for Aqueduct documentation.
