### ISSUE TITLE
Create dynamic UI design for plugin parameters collection

### ISSUE THREAD

**Issue by str-anger** [AqueductHub/aqueductcore#60]
The screen is generated according to endpoint declaration and builds a form to populate with values.
To start these might be:
- Experiment dropdown (with search) -- PROBABLY if we don't add this to experiment UI
- File dropdown inside experiment
- string, multiline string, float, int.

**Comment by gabrielg42** [comment]
@str-anger @jatinriverlane @safeamiiir @gabrielg42 pls review
