### ISSUE TITLE
Document `aqueductcore-dev` docker image in `README.md` 

### ISSUE THREAD

**Issue by JMuff22** [AqueductHub/aqueductcore#75]
Pushes to main deploy the `aqueductcore-dev` docker image to dockerhub: https://hub.docker.com/r/aqueducthub/aqueductcore-dev . This should be added to the `README.md` to tell users that this exists. Probably some disclaimer that this may be unstable.

**Comment by JMuff22** [comment]
Additionally, it could be added to the documentation.

**Comment by samiralavi** [comment]
Hi @JMuff22, a new section has been added to the README.md file in my PR. For now, we keep it here in the README.md file but later once we design our developers section on the documentation, it will be there.
