### ISSUE TITLE
API enhancement request

### ISSUE THREAD

**Issue by safeamiiir** [AqueductHub/aqueductcore#82]
**Describe the bug**
It's a request to modify API fields for better simplicity and common sense alignment.

**Current API**
1- The unique identifier which is referred to by the name `id` is better to be changed to `uuid`
2- The experiment id which is referred to by the name `alias` is better to be changed to `eid` 
3- Also, it's good to separate the `favourite` and `archive` functionality from being a special tag and being considered as a field in the Database which improves query efficiency and API usage.

**Additional context**
I also see that there will be breaking changes with `Aqueduct-core` and `pyAqueduct`.

**Comment by samiralavi** [comment]
@safeamiiir about the `uuid` field, I guess we still want to continue using that in our GraphQL API? Can web establish that GraphQL API is based on `uuid` and GUI and PyAqueduct (the user-facing parts of Aqueduct) use cases are based on `eid`?
